CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE NOVEL_SEQ;
CREATE SEQUENCE SUBNOVEL_SEQ;
CREATE SEQUENCE NOVELREPLY_SEQ;
CREATE SEQUENCE COIN_SEQ;
CREATE SEQUENCE SUPPORT_SEQ;
CREATE SEQUENCE BUYCHAPTER_SEQ;
CREATE SEQUENCE MYILLU_SEQ;
CREATE SEQUENCE NOVELFILE_SEQ;
CREATE SEQUENCE ILLUFILE_SEQ;
CREATE SEQUENCE CHAT_SEQ;
CREATE SEQUENCE MESSAGE_SEQ;
CREATE SEQUENCE MESSAGEFIL_SEQ;
CREATE SEQUENCE ILLUBUYLIST_SEQ;

/*회원*/
CREATE TABLE TBL_USER(
	USERNUM NUMBER PRIMARY KEY,
	USERID VARCHAR2(1000),
	USERPW VARCHAR2(1000),
	USERNICK VARCHAR2(1000),
	USEREMAIL VARCHAR2(1000),
	USERGENDER NUMBER,
	USERPHONENUM VARCHAR2(1000),
	USERSTATUS NUMBER,
	REPORTCOUNT NUMBER,
	CHARGEAMOUNT NUMBER,
	COINBALANCE NUMBER, /*코인 잔액*/
	NOVELSPONAMOUNT NUMBER, /*받은 소설 후원금액*/
	ILLUSPONAMOUNT NUMBER, /*받은 일러스트 후원금액*/
	KAKAO_NUMBER NUMBER,
	CONSTRAINT FK_KAKAO FOREIGN KEY(KAKAO_NUMBER) REFERENCES TBL_KAKAO(KAKAO_NUMBER)
);



/* 카카오 로그인*/
CREATE TABLE TBL_KAKAO (
	KAKAO_NUMBER NUMBER PRIMARY KEY,
    KAKAO_NAME varchar(20) not null,
    KAKAO_EMAIL varchar(50) not NULL
);

SELECT * FROM TBL_USER;

INSERT INTO TBL_USER
(USERNUM, USERID, USERPW, USERNICK, USEREMAIL, USERGENDER, USERPHONENUM, USERSTATUS, CHARGEAMOUNT, COINBALANCE, NOVELSPONAMOUNT, ILLUSPONAMOUNT)
VALUES(USER_SEQ.NEXTVAL, 'sjm1234', '#sjm1234', '재민', 'skminy27@nate.com', 0, '01089087253', 0, 0, 0, 0, 0);


/*소설(목록)*/
CREATE TABLE TBL_NOVEL(
	NOVEL_NOVELNUM NUMBER PRIMARY KEY,
	USER_USERNUM NUMBER, /*FK, 작성자 회원번호*/
	NOVEL_NOVELTITLE VARCHAR2(1000),
	NOVEL_USERNICK VARCHAR2(1000),
	NOVEL_HASHTAG VARCHAR2(1000), /*예) #로맨스 #메카물 #마법사*/
	NOVEL_UPLOADDATE DATE DEFAULT SYSDATE, /* 등록일 */
	NOVEL_UPDATEDATE DATE DEFAULT SYSDATE,  /* */
	
	NOVEL_NOVELWEEKMONDAY NUMBER, /*요일 컬럼 7개 받아야 하는지 하나로 해야하는지*/
	/* 이런식으로 월~ 금  1이면 연재*/
	NOVEL_NOVELCATEGORY VARCHAR2(1000), /* 큰 카테고리 첫번째 태그 연결*/
	NOVEL_NOVELMYPICK NUMBER, /*"찜횟수"*/
	NOVEL_TOTALSPONAMOUNT NUMBER, /*총후원금액*/
	NOVEL_NOVELSTATUS NUMBER, /*작품 상태 0휴재, 1연재, 2완결, 3 숨김*/
	NOVEL_SERIALSTATUS NUMBER, /*정기연재 OR 자유연재 상태*/
	NOVEL_CONTENT VARCHAR2(1000), /* 소설 소개*/
	CONSTRAINT FK_USERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)	
); 


/*소설(한 회차)*/
CREATE TABLE TBL_SUBNOVEL(
	SUBNOVEL_CHAPTERNUM NUMBER PRIMARY KEY,
	SUBNOVEL_NOVELNUM NUMBER,/*FK*/
	SUBNOVEL_NOVELTITLE VARCHAR2(1000),
	SUBNOVEL_NOVELSUBTITLE VARCHAR2(1000), /*소제목*/
	SUBNOVEL_WRITERCOMMENT, /*작가의 작품 후기(매 회차 마다)*/
	SUBNOVEL_USERNICK VARCHAR2(1000),
	SUBNOVEL_UPLOADDATE DATE DEFAULT SYSDATE,
	SUBNOVEL_UPDATEDATE DATE DEFAULT SYSDATE,
	SUBNOVEL_VIEWCOUNT NUMBER, /*조회수*/
	SUBNOVEL_LIKECOUNT NUMBER, /*좋아요 수*/
	SUBNOVEL_STATUS NUMBER /*회차 상태 0 숨김, 1 보여짐*/,
	
	CONSTRAINT fk_NOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM)
	
);

/*소설원고파일*/
CREATE TABLE TBL_NOVELFILE(
	NOVELFILENUM NUMBER PRIMARY KEY, /*파일번호, 소설원고*/
	SUBNOVEL_CHAPTERNUM NUMBER, /* FK */
	USERNUM NUMBER,
	USERNICK VARCHAR2(1000),
	FILEPATH VARCHAR2(1000),
	ORIGINFILENAME VARCHAR2(1000),
	FILENAME VARCHAR2(1000),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT fk_SUBNOVELFILE FOREIGN KEY(SUBNOVEL_CHAPTERNUM) REFERENCES TBL_SUBNOVEL(SUBNOVEL_CHAPTERNUM)
);





/*한 회차의 댓글*/
CREATE TABLE TBL_NOVELREPLY(
	REPLYNUM NUMBER PRIMARY KEY,
	USERNUM  NUMBER FK
	REPLYCONTENT VARCHAR2(3000),
	REPLYUPLOADDATE DATE DEFAULT SYSDATE, /*댓글 작성 시간*/
	REPLYUPDATEDATE DATE DEFAULT SYSDATE, /*댓글 수정 시간*/
	REPLYUP NUMBER, /*추천*/
	REPLYDOWN NUMBER, /*비추천*/
	REPLYREPORT NUMBER/*신고*/
	/*REPLYEMOTE(보류중)*/
	/*PROFILEPICTURE(보류중)*/
);


/* 일러스트 작가 프로필*/
CREATE TABLE TBL_ILLUPROFILE(

/*  일러스트 작가프로필 NUM - PK
 *  유저번호 FK  
 *  로그인 ID 
    닉네임 
    짧은소개 
    자세한 소개 
    주 활동영역 (카테고리)
    웹사이트 
 * */
	FINISHWORKCOUNT NUMBER, /*완료한 작업 개수*/

);

/*코인 결제내역(캐쉬충전, 현금을 코인으로)*/
CREATE TABLE TBL_COIN(
	PAYNUM NUMBER PRIMARY KEY, /*거래번호*/
	USERNUM NUMBER,/*FK*/
	CHARGEAMOUNT NUMBER, /*실제 사용자가 결제한 금액*/
	COINCOUNT NUMBER,/*환전된 코인*/
	ORDERDATE DATE,
	STATUS NUMBER , /* 환불 및 기타 상태 */
	CONSTRAINT FK_COINUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);  /********테이블 생성 오류?*/




/*후원(전체, 회차)*/
CREATE TABLE TBL_SUPPORT(
	SPONNUM NUMBER PRIMARY KEY,
	SPONSER VARCHAR(1000), /*후원한 사람, USERNUM으로 불러와야할듯*/
	RESPONSOR NUMBER, /*FK, 후원 받은 사람*/
	NOVELNUM NUMBER, /*FK, 소설 번호*/
	SPONAMOUNT NUMBER, /*후원 금액 = 차감 코인*/
	SPONDATE DATE DEFAULT SYSDATE, /*후원 날짜*/
	CONSTRAINT FK_RESPONSOR FOREIGN KEY(RESPONSOR) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_SUPNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM)
);


/*회차 구매내역*/
CREATE TABLE TBL_BUYCHAPTER(
	BUYNUM NUMBER PRIMARY KEY, /*회차 구매번호*/
	NOVELNUM NUMBER, /*FK, 소설번호*/
	CHAPTERNUM NUMBER, /*FK, 회차번호*/
	USERNUM NUMBER,/* FK 구매한 유저 */
	MINUSCOINNUMBER, /*차감코인*/
	BUYDATE DATE DEFAULT SYSDATE, /*구매날짜*/
	BUYSTATUS NUMBER,
	USERNUM NUMBER,
	CONSTRAINT FK_BUYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_CHAPTERNUM FOREIGN KEY(CHAPTERNUM) REFERENCES TBL_SUBNOVEL(CHAPTERNUM)
	/*FK추가*/
);




/*찜한 소설*/
CREATE TABLE TBL_MYNOVEL(
	NOVELNUM NUMBER, /*FK*/
	NEWCHAPTERSTATUS NUMBER, 
	USERNUM NUMBER(5), /*FK*/
	CONSTRAINT FK_MYMYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_MYMYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);


/*일러스트*/
CREATE TABLE TBL_ILLU(
	ILLUNUM NUMBER PRIMARY KEY,
	/*작가 USERNUM - FK */
	ILLUTITLE VARCHAR2(1000),
	ILLUCONTENT VARCHAR2(3000),
	ILLUREGDATE DATE DEFAULT SYSDATE,     /* 작성 시간*/
	ILLUUPDATEDATE DATE DEFAULT SYSDATE, /* 수정시간 */
	ILLUHASHTAG VARCHAR2(1000), /*해시태그*/
	ILLUVIEWCOUNT NUMBER, /*조회수*/
	ILLULIKE NUMBER, /*각 일러스트에 대한 좋아요*/
	INTRODUTION VARCHAR2(1000), /*작품에 대한 짧은 소개*/
	 /* 케이케이드 */
);

/*찜한 일러스트*/
CREATE TABLE TBL_MYILLU(
	ILLUNUM NUMBER, /*FK*/
	USERNUM NUMBER, /*FK, 찜한 회원번호*/
	CONSTRAINT FK_ILLUUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_ILLUNUM FOREIGN KEY(ILLUNUM) REFERENCES TBL_MYILLU(ILLUNUM)
);

/* 최근 본 작품 */
CREATE TABLE TBL_RECENTVIEW(
	RECENTVIEW_NUMBER NUMBER PRIMARY KEY, /* 최근 본 작품 번호*/
	USER_USERNUM NUMBER,
	CONSTRAINT FK_RECENTVIEWUSERNUM FOREIGN KEY(USER_USERNUM) REFERENCES TBL_USER(USER_USERNUM)
);




/* 소설 표지파일 */
CREATE TABLE TBL_NOVELIMGFILE(
	NOVELIMGFILE_FILENUM NUMBER PRIMARY KEY,
	-- 소설NUM FK 
	USER_USERNUM NUMBER,
	NOVELIMGFILE_FILEPATH VARCHAR2(1000),
	NOVELIMGFILE_ORIGINFILENAME VARCHAR2(1000),
	NOVELIMGFILE_FILENAME VARCHAR2(1000),
	NOVELIMGFILE_UPLOADDATE DATE DEFAULT SYSDATE,
	NOVELIMGFILE_UPDATEDATE DATE DEFAULT SYSDATE,
	
	-- USER_USERNUM FK
	-- 소설 NUMBER FK  
);

/*일러스트 이미지파일*/
CREATE TABLE TBL_ILLUIMGFILE(
	ILLUFILENUM NUMBER PRIMARY KEY,
	ILLUNUM /* 일러스트 게시글 번호 */
	USERNUM NUMBER,
	FILEPATH VARCHAR2(1000),
	ORIGINFILENAME VARCHAR2(1000),
	FILENAME VARCHAR2(1000),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
	-- FK USERNUM
);

/* 프로필 이미지파일*/
CREATE TABLE TBL_PROFILEIMGFILE(
	PROFILEIMGFILE_PROFILEIMGNUM NUMBER PRIMARY KEY,
	USER_USERNUM NUMBER,
	PROFILEIMGFILE_FILEPATH VARCHAR2(1000),
	PROFILEIMGFILE_ORIGINFILENAME VARCHAR2(1000),
	PROFILEIMGFILE_FILENAME VARCHAR2(1000),
	PROFILEIMGFILE_UPLOADDATE DATE DEFAULT SYSDATE,
	PROFILEIMGFILE_UPDATEDATE DATE DEFAULT SYSDATE,
	-- USER_USERNUM FK 
);

/*소켓사용 채팅 구현*/
/*채팅,결제 관련 테이블(일러스트)*/
/*일러스트 작가 <-> 글작가 코인*/


/*채팅(방)*/
CREATE TABLE TBL_CHAT(
	CHATNUM NUMBER PRIMARY KEY,
	USERNUM NUMBER, /*목록 소유자*/
	SENDERNUM NUMBER, /*보낸 사람*/
	CREATIONDATE DATE DEFAULT SYSDATE /*생성날짜*/	
	/* 케스케이드 */
);


/*메시지*/
CREATE TABLE TBL_MESSAGE(
	MESSAGENUM NUMBER PRIMARY KEY,
	CHATNUM NUMBER, /*FK*/
	USERNUM NUMBER, /*FK, 작성자 회원번호*/
	GETUSERNUM NUMBER,/*FK, 받는 사람 USERNUM*/
	MESSAGECONTENT VARCHAR2(3000),
	CONSTRAINT FK_CHATNUM FOREIGN KEY(CHATNUM) REFERENCES TBL_CHAT(CHATNUM),
	CONSTRAINT FK_CHATUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_CHATGETUSERNUM FOREIGN KEY(GETUSERNUM) REFERENCES TBL_USER(USERNUM)
	/* 케스케이드 */
);


/*메시지 첨부파일*/
CREATE TABLE TBL_MESSAGEFILE(
	MESSAGEFILE_MESSAGEFILENUM NUMBER PRIMARY KEY,
	CHATNUM NUMBER, /*FK*/
	SENDUSERNUM NUMBER, /*FK, 보내는 사람 USERNUM*/
	GETUSERNUM NUMBER,/*FK, 받는 사람 USERNUM*/
	MESSAGEFILEPATH VARCHAR2(1000),
	ORIGINFILENAME VARCHAR2(1000),
	FILENAME VARCHAR2(1000),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_FILECHATNUM FOREIGN KEY(CHATNUM) REFERENCES TBL_CHAT(CHATNUM),
	CONSTRAINT FK_SENDUSERNUM FOREIGN KEY(SENDUSERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_GETUSERNUM FOREIGN KEY(GETUSERNUM) REFERENCES TBL_USER(USERNUM)
);

CREATE TABLE TBL_INQUIRY(

/*
닉네임 
제목
내용
답변 
처리상태
등록일 
*/

);


/*일러스트 구매내역*/
CREATE TABLE TBL_ILLUBUYLIST(
	PAYMENTNUM NUMBER PRIMARY KEY,
	ILLUNUM NUMBER, /*FK*/
	USERNICK VARCHAR2(1000), 
	BUYDATE DATE DEFAULT SYSDATE,
	USERNUM NUMBER, /*FK, 구매한 사람*/
	CONSTRAINT FK_ILLUNUM FOREIGN KEY(ILLUNUM) REFERENCES TBL_MYILLU(ILLUNUM), /*ILLUFILEPATH PK추가 후*/
	CONSTRAINT FK_ILLUBUYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);






-- 필요없어진 테이블
/*내 서재*/

CREATE TABLE TBL_MYLIBRARY(
	COLLECTION VARCHAR2(1000) PRIMARY KEY, /*소장 작품*/
	RECENTRECORD NUMBER, /*작품번호, 회차번호, 열람시간*/
	NOVELNUM NUMBER, /*FK, 찜한 작품을 소설 번호로 가져온다*/
	USERNUM NUMBER, /*FK*/
	CONSTRAINT FK_MYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_MYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);




