CREATE SEQUENCE USER_SEQ;

/*회원*/
CREATE TABLE TBL_USER(
	USERNUM NUMBER(36) AUTO_INCREMENT PRIMARY KEY,
	USERID VARCHAR2(360),
	USERPW VARCHAR2(360),
	USERNICK VARCHAR2(360),
	USEREMAIL VARCHAR2(360),
	USERGENDER NUMBER(36),
	USERPHONENUM VARCHAR2(360),
	USERSTATUS NUMBER(36),
	CHARGEAMOUNT NUMBER(36),
	POINTBALANCE NUMBER(36), /*포인트 잔액*/
	NOVELSPONAMOUNT NUMBER(36), /*받은 소설 후원금액*/
	ILLUSPONAMOUNT NUMBER(36) /*받은 일러스트 후원금액*/
);

CREATE SEQUENCE NOVEL_SEQ;

/*소설(목록)*/
CREATE TABLE TBL_NOVEL(
	NOVELNUM NUMBER(36) PRIMARY KEY,
	USERNUM NUMBER(36), /*FK, 작성자 회원번호*/
	NOVELTITLE VARCHAR2(360),
	USERNICK VARCHAR2(360),
	HASHTAG VARCHAR2(360), /*예) #로맨스 #메카물 #마법사*/
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	/*NOVELWEEK VARCHAR2(360),*/ /*요일 컬럼 7개 받아야 하는지 하나로 해야하는지*/
	NOVELCATEGORY VARCHAR2(360),
	NOVELWISHCOUNT NUMBER(36), /*"찜횟수"*/
	TOTALSPONAMOUNT NUMBER(36), /*총후원금액*/
	NOVELSTATUS NUMBER(36), /*작품 상태 0휴재, 1연재, 2완결*/
	SERIALSTATUS NUMBER(36), /*정기연재 OR 자유연재 상태*/
	CONSTRAINT FK_USERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);

CREATE SEQUENCE SUBNOVEL_SEQ;

/*소설(한 회차)*/
CREATE TABLE TBL_SUBNOVEL(
	CHAPTERNUM NUMBER(36) PRIMARY KEY,
	NOVELNUM NUMBER(36),/*FK*/
	NOVELTITLE VARCHAR2(360),
	USERNICK VARCHAR2(360),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	/*NOVELWEEK VARCHAR2(360), */
	VIEWCOUNT NUMBER(36), /*조회수*/
	LIKECOUNT NUMBER(36), /*좋아요 수*/
	/*...*/
	CONSTRAINT fk_NOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM)
);

CREATE SEQUENCE NOVELREPLY_SEQ;

/*한 회차의 댓글*/
CREATE TABLE TBL_NOVELREPLY(
	REPLYNUM NUMBER(36) PRIMARY KEY,
	USERNICK VARCHAR2(360),
	REPLYCONTENT VARCHAR2(3000),
	REPLYUPLOADDATE DATE DEFAULT SYSDATE, /*댓글 작성 시간*/
	REPLYUPDATEDATE DATE DEFAULT SYSDATE, /*댓글 수정 시간*/
	REPLYUP NUMBER(36), /*추천*/
	REPLYDOWN NUMBER(36), /*비추천*/
	REPLYREPORT NUMBER(36)/*신고*/
	/*REPLYEMOTE(보류중)*/
	/*PROFILEPICTURE(보류중)*/
);

CREATE SEQUENCE POINT_SEQ;

/*포인트 결제(캐쉬충전, 현금을 포인트로)*/
CREATE TABLE TBL_POINT(
	PAYNUM NUMBER(36) PRIMARY KEY, /*거래번호*/
	USERNUM NUMBER(36),/*FK*/
	CHARGEAMOUNT NUMBER(36), /*실제 사용자가 결제한 금액*/
	POINT NUMBER(36),/*환전된 포인트*/
	CONSTRAINT FK_POINTUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);  /********테이블 생성 오류?*/

CREATE SEQUENCE SUPPORT_SEQ;

/*후원(전체, 회차)*/
CREATE TABLE TBL_SUPPORT(
	SPONNUM NUMBER(36) PRIMARY KEY,
	SPONSER VARCHAR(360), /*후원한 사람, USERNUM으로 불러와야할듯*/
	RESPONSOR NUMBER(36), /*FK, 후원 받은 사람*/
	NOVELNUM NUMBER(36), /*FK, 소설 번호*/
	SPONAMOUNT NUMBER(36), /*후원 금액 = 차감 포인트*/
	SPONDATE DATE DEFAULT SYSDATE, /*후원 날짜*/
	CONSTRAINT FK_RESPONSOR FOREIGN KEY(RESPONSOR) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_SUPNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM)
);

CREATE SEQUENCE BUYCHAPTER_SEQ;

/*회차 구매*/
CREATE TABLE TBL_BUYCHAPTER(
	BUYNUM NUMBER(36) PRIMARY KEY, /*회차 구매번호*/
	NOVELNUM NUMBER(36), /*FK, 소설번호*/
	CHAPTERNUM NUMBER(36), /*FK, 회차번호*/
	MINUSPOINT NUMBER(36), /*차감포인트*/
	BUYDATE DATE DEFAULT SYSDATE, /*구매날짜*/
	BUYSTATUS NUMBER(36),
	USERNUM NUMBER(36),
	CONSTRAINT FK_BUYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_CHAPTERNUM FOREIGN KEY(CHAPTERNUM) REFERENCES TBL_SUBNOVEL(CHAPTERNUM)
);
/*FK추가*/

/*내 서재*/
CREATE TABLE TBL_MYLIBRARY(
	COLLECTION VARCHAR2(360) PRIMARY KEY, /*소장 작품*/
	RECENTRECORD NUMBER(36), /*작품번호, 회차번호, 열람시간*/
	NOVELNUM NUMBER(36), /*FK, 찜한 작품을 소설 번호로 가져온다*/
	USERNUM NUMBER(36), /*FK*/
	CONSTRAINT FK_MYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_MYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);

/*찜한 소설*/
CREATE TABLE TBL_MYNOVEL(
	NOVELNUM NUMBER(36), /*FK*/
	NEWCHAPTERSTATUS NUMBER(36), 
	USERNUM NUMBER(5), /*FK*/
	CONSTRAINT FK_MYMYNOVELNUM FOREIGN KEY(NOVELNUM) REFERENCES TBL_NOVEL(NOVELNUM),
	CONSTRAINT FK_MYMYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);

CREATE SEQUENCE MYILLU_SEQ;

/*일러스트*/
CREATE TABLE TBL_MYILLU(
	ILLUNUM NUMBER(36) PRIMARY KEY,
	ILLUTITLE VARCHAR2(360),
	ILLUCONTENT VARCHAR2(3000),
	USERNICK VARCHAR2(360)
);

/*찜한 일러스트*/
CREATE TABLE TBL_ILLU(
	ILLUNUM NUMBER(36), /*FK*/
	USERNUM NUMBER(36), /*FK, 찜한 회원번호*/
	CONSTRAINT FK_ILLUUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_ILLUNUM FOREIGN KEY(ILLUNUM) REFERENCES TBL_MYILLU(ILLUNUM)
);

CREATE SEQUENCE NOVELFILE_SEQ;

/*소설원고파일*/
CREATE TABLE TBL_NOVELFILE(
	NOVELFILENUM NUMBER(36) PRIMARY KEY, /*파일번호, 소설원고*/
	USERNUM NUMBER(36),
	USERNICK VARCHAR2(360),
	FILEPATH VARCHAR2(360),
	ORIGINFILENAME VARCHAR2(360),
	FILENAME VARCHAR2(360),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE ILLUFILE_SEQ;

/*일러스트 이미지파일*/
CREATE TABLE TBL_ILLUFILE(
	ILLUFILENUM NUMBER(36) PRIMARY KEY,
	USERNUM NUMBER(36),
	FILEPATH VARCHAR2(360),
	ORIGINFILENAME VARCHAR2(360),
	FILENAME VARCHAR2(360),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

/*소켓사용 채팅 구현*/
/*채팅,결제 관련 테이블(일러스트)*/
/*일러스트 작가 <-> 글작가 포인트*/

CREATE SEQUENCE CHAT_SEQ;

/*채팅(방)*/
CREATE TABLE TBL_CHAT(
	CHATNUM NUMBER(36) PRIMARY KEY,
	USERNUM NUMBER(36), /*목록 소유자*/
	SENDERNUM NUMBER(36), /*보낸 사람*/
	CREATIONDATE DATE DEFAULT SYSDATE /*생성날짜*/	
);

CREATE SEQUENCE MESSAGE_SEQ;

/*메시지*/
CREATE TABLE TBL_MESSAGE(
	MESSAGENUM NUMBER(36) PRIMARY KEY,
	CHATNUM NUMBER(36), /*FK*/
	USERNUM NUMBER(36), /*FK, 작성자 회원번호*/
	GETUSERNUM NUMBER(36),/*FK, 받는 사람 USERNUM*/
	MESSAGECONTENT VARCHAR2(3000),
	CONSTRAINT FK_CHATNUM FOREIGN KEY(CHATNUM) REFERENCES TBL_CHAT(CHATNUM),
	CONSTRAINT FK_CHATUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_CHATGETUSERNUM FOREIGN KEY(GETUSERNUM) REFERENCES TBL_USER(USERNUM)
);

CREATE SEQUENCE MESSAGEFILE_SEQ;

/*메시지 첨부파일*/
CREATE TABLE TBL_MESSAGEFILE(
	MESSAGEFILENUM NUMBER(36) PRIMARY KEY,
	CHATNUM NUMBER(36), /*FK*/
	SENDUSERNUM NUMBER(36), /*FK, 보내는 사람 USERNUM*/
	GETUSERNUM NUMBER(36),/*FK, 받는 사람 USERNUM*/
	MESSAGEFILEPATH VARCHAR2(360),
	ORIGINFILENAME VARCHAR2(360),
	FILENAME VARCHAR2(360),
	UPLOADDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT FK_FILECHATNUM FOREIGN KEY(CHATNUM) REFERENCES TBL_CHAT(CHATNUM),
	CONSTRAINT FK_SENDUSERNUM FOREIGN KEY(SENDUSERNUM) REFERENCES TBL_USER(USERNUM),
	CONSTRAINT FK_GETUSERNUM FOREIGN KEY(GETUSERNUM) REFERENCES TBL_USER(USERNUM)
);

CREATE SEQUENCE ILLUBUYLIST_SEQ;

/*일러스트 구매내역*/
CREATE TABLE TBL_ILLUBUYLIST(
	PAYMENTNUM NUMBER(36) PRIMARY KEY,
	ILLUNUM NUMBER(36), /*FK*/
	USERNICK VARCHAR2(360), 
	BUYDATE DATE DEFAULT SYSDATE,
	USERNUM NUMBER(36), /*FK, 구매한 사람*/
	CONSTRAINT FK_ILLUNUM FOREIGN KEY(ILLUNUM) REFERENCES TBL_MYILLU(ILLUNUM), /*ILLUFILEPATH PK추가 후*/
	CONSTRAINT FK_ILLUBUYUSERNUM FOREIGN KEY(USERNUM) REFERENCES TBL_USER(USERNUM)
);