BEGIN
	DBMS_OUTPUT.PUT_LINE('HELLO');
END;

--F(X) = 2X + 1

CREATE OR REPLACE PROCEDURE HR.F
(
   X NUMBER 
)
IS
BEGIN 
   DBMS_OUTPUT.PUT_LINE(2 * X + 1);
END;

CALL F(2);
----------------------------------------------------
DECLARE
   SCORE NUMBER := 88;
   GRADE VARCHAR2(5);
BEGIN
   IF SCORE >= 90 THEN GRADE := 'A';
   ELSIF SCORE >= 80 THEN GRADE := 'B';
   ELSIF SCORE >= 70 THEN GRADE := 'C';
   ELSIF SCORE >= 60 THEN GRADE := 'D';
   ELSE GRADE := 'F';
   END IF;
   DBMS_OUTPUT.PUT_LINE('당신의 점수 : ' ||SCORE||'점'||CHR(10)||'학점 : '||GRADE);
END;

CREATE OR REPLACE PROCEDURE SCORETEST
(
	 	SCORE  NUMBER
)
IS
	GRADE VARCHAR2(5)
BEGIN 
   IF SCORE >= 90 THEN GRADE := 'A';
   ELSIF SCORE >= 80 THEN GRADE := 'B';
   ELSIF SCORE >= 70 THEN GRADE := 'C';
   ELSIF SCORE >= 60 THEN GRADE := 'D';
   ELSE GRADE := 'F'; DBMS_OUTPUT.PUT_LINE('넌 소중해');
   END IF;
   DBMS_OUTPUT.PUT_LINE('당신의 점수 : ' ||SCORE||'점'||CHR(10)||'학점 : '||GRADE);
END;

DROP PROCEDURE SCORETEST;
CALL SCORETEST(60);
-- 프로시저 사용시 오라클 오류가 존재
-- IS구분에 변수 선언시 ; 을 빼고 저장후 다시 붙여서 저장해야한다. 


SELECT * FROM JOBS;

CREATE OR REPLACE PROCEDURE PROC_NEW_JOB
(
   P_JOB_ID IN JOBS.JOB_ID%TYPE,
   P_JOB_TITLE IN JOBS.JOB_TITLE%TYPE,
   P_MIN_SALARY IN JOBS.MIN_SALARY%TYPE,
   P_MAX_SALARY IN JOBS.MAX_SALARY%TYPE
)
IS
BEGIN 
   INSERT INTO JOBS
   (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
   VALUES(P_JOB_ID, P_JOB_TITLE, P_MIN_SALARY, P_MAX_SALARY);
   DBMS_OUTPUT.PUT_LINE('ALL DONE ABOUT '||P_JOB_ID);
END;

CALL PROC_NEW_JOB('IT', 'Developer', 14000, 50000);

SELECT * FROM JOBS;


CREATE OR REPLACE PROCEDURE PROC_REMOVE_JOB
(
	P_JOB_ID IN JOBS.JOB_ID%TYPE
)
IS 
BEGIN 
	DELETE FROM JOBS
	WHERE JOB_ID=P_JOB_ID;
END;


CALL PROC_REMOVE_JOB('IT');





CREATE OR REPLACE PROCEDURE PROC_DEL_JOB
(
   P_JOB_ID JOBS.JOB_ID%TYPE
)
IS
   CNT NUMBER := 0;
BEGIN
   SELECT COUNT(JOB_ID) INTO CNT FROM JOBS
   WHERE JOB_ID = P_JOB_ID;
   IF CNT != 0
   THEN
      DELETE FROM JOBS
      WHERE JOB_ID = P_JOB_ID;
      DBMS_OUTPUT.PUT_LINE('DELETE ALL DONE ABOUT '||P_JOB_ID);
   ELSE
      DBMS_OUTPUT.PUT_LINE('NOT EXIST '||P_JOB_ID);
   END IF;
END;



DROP PROCEDURE PROC_DEL_JOB;
CALL PROC_DEL_JOB('IT'); 

------------------------------------------------------------------------------
-- JOBS 테이블에 데이터를 전달받은 후 INSERT 하는 프로시저 제작
-- 만약 INSERT가 되지 않는다면 UPDATE를 하도록 구현
CREATE OR REPLACE PROCEDURE PROC_NEW_JOB_OR_UPDATE_JOB
(
   P_JOB_ID IN JOBS.JOB_ID%TYPE,
   P_JOB_TITLE IN JOBS.JOB_TITLE%TYPE,
   P_MIN_SALARY IN JOBS.MIN_SALARY%TYPE,
   P_MAX_SALARY IN JOBS.MAX_SALARY%TYPE
)
IS
   CNT NUMBER := 0;
BEGIN
   SELECT COUNT(JOB_ID) INTO CNT FROM JOBS WHERE JOB_ID = P_JOB_ID;
   IF CNT = 0
   THEN
      INSERT INTO JOBS
      (JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY)
      VALUES(P_JOB_ID, P_JOB_TITLE, P_MIN_SALARY, P_MAX_SALARY);
      DBMS_OUTPUT.PUT_LINE('INSERT ALL DONE ABOUT '||P_JOB_ID);
   ELSE
      UPDATE JOBS
      SET JOB_TITLE = P_JOB_TITLE, MIN_SALARY = P_MIN_SALARY, MAX_SALARY = P_MAX_SALARY
      WHERE JOB_ID = P_JOB_ID;
      DBMS_OUTPUT.PUT_LINE('UPDATE ALL DONE ABOUT '||P_JOB_ID);
   END IF;
END;

CALL PROC_NEW_JOB_OR_UPDATE_JOB('IT', 'Developer', 14000, 50000); 

SELECT * FROM JOBS;


